version: '3.8'

services:
  db-monitoring:
    image: mysql:9.0
    container_name: db-monitoring
    environment:
      MYSQL_DATABASE: monitoring
      MYSQL_ROOT_PASSWORD: qwerty1234
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-employees:
    image: mysql:9.0
    container_name: db-employees
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ROOT_PASSWORD: qwerty1234
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  employee-service:
    build:
      context: .
      dockerfile: employees/Dockerfile
    container_name: employee-service
    depends_on:
      db-employees:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-employees:3306/employees
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qwerty1234
      - SPRING_LIQUIBASE_ENABLED=true
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  monitoring-service:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    container_name: monitoring-service
    depends_on:
      db-monitoring:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      employee-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-monitoring:3306/monitoring
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qwerty1234
      - SPRING_LIQUIBASE_ENABLED=true
    volumes:
      - ./logs/monitoring:/app/log
    ports:
      - "8081:8081"
