spring.application.name=monitoring-service
server.servlet.encoding.charset=UTF-8
server.port=8081
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
#spring.liquibase.enabled=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/monitoring}
spring.datasource.username=root
spring.datasource.password=qwerty1234
spring.mvc.format.date=yyyy-MM-dd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.logback.rollingpolicy.max-file-size=10mb
spring.session.timeout=480m
logging.file.name=./log/application.log
logging.level.root=info
spring.liquibase.change-log=classpath:db/changelog/db.changelog-monitoring.yml
