databaseChangeLog:
  - changeSet:
      id: 20260307-2
      author: Oleg Alikin
#      preConditions:
#        - onFail: MARK_RAN
#        - not:
#          tableExists:
#            tableName: application_log
      changes:
        - createTable:
            tableName: application_log
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    primaryKeyName: application_log_pkey
                    nullable: false
              - column:
                  name: operation
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: request_time
                  type: DATETIME
                  constraints:
                    nullable: false
